Repository ZeroGachis/xamarin-ui, pull requests merged in 2020-10, with the labels that each got.

#5 ✨ Add markup extension to use Embedded Res as Image on XAML
  Smartway.UiComponent.Sample/SectionSheet/SectionSheetSample.xaml
  Smartway.UiComponent/Resources/Images/logo_easyturn.png
  Smartway.UiComponent/Smartway.UiComponent.csproj
  Smartway.UiComponent/Utils/ImageResourceExtension.cs
Labels: To Review, enhancement

#4 Feature/article card component
  Smartway.UiComponent.Sample.Android/NotifyMessageAndroid.cs
  Smartway.UiComponent.Sample.Android/Smartway.UiComponent.Sample.Android.csproj
  Smartway.UiComponent.Sample/INotifyMessage.cs
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/SectionSheet/SectionSheetSample.xaml
  Smartway.UiComponent.Sample/SectionSheet/ViewModels/SectionSheetSampleViewModel.cs
  Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
  Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml.cs
  Smartway.UiComponent/Resources/Images/img_product_placeholder.png
  Smartway.UiComponent/Resources/Images/img_product_placeholder_multilocation.png
  Smartway.UiComponent/Resources/Resources.Designer.cs
  Smartway.UiComponent/Resources/Resources.resx
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#8 ✨ add Article Card component
  Smartway.UiComponent.Sample/DummyArticle.cs
  Smartway.UiComponent.Sample/SectionSheet/ViewModels/SectionSheetSampleViewModel.cs
  Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
  Smartway.UiComponent/Resources/Images/img_product_placeholder.png
  Smartway.UiComponent/Separators/ElementSeparator.xaml
  Smartway.UiComponent/Separators/ElementSeparator.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task

#7 Feature/add expander card
  Smartway.UiComponent.Sample.Android/MainActivity.cs
  Smartway.UiComponent.Sample.Android/Smartway.UiComponent.Sample.Android.csproj
  Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml
  Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Cards/CustomExpander.xaml
  Smartway.UiComponent/Cards/CustomExpander.xaml.cs
  Smartway.UiComponent/Cards/ExpanderCard.xaml
  Smartway.UiComponent/Cards/ExpanderCard.xaml.cs
  Smartway.UiComponent/Cards/RoundedFrame.xaml
  Smartway.UiComponent/Cards/RoundedFrame.xaml.cs
  Smartway.UiComponent/Resources/Colors.xaml
  Smartway.UiComponent/Resources/Icons/black_icon_arrow_down.png
  Smartway.UiComponent/Resources/Icons/orange_icon_arrow_down.png
  Smartway.UiComponent/Resources/Icons/orange_icon_warning.png
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review

#10 :lipstick: Fix topappbar in order to not have background and margin
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
Labels: To Review, bug

#9 Task/labelled divider component
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Separator/SeparatorsSample.xaml
  Smartway.UiComponent.Sample/Separator/SeparatorsSample.xaml.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Separators/LabelledDivider.xaml
  Smartway.UiComponent/Separators/LabelledDivider.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#11 Feature/improve primary button
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent.Sample/Buttons/Button.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/SectionFormSample.xaml
  Smartway.UiComponent.Sample/SectionFormSampleViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Buttons/Button.xaml
  Smartway.UiComponent/Buttons/Button.xaml.cs
  Smartway.UiComponent/Buttons/PrimaryButton.xaml
  Smartway.UiComponent/Buttons/PrimaryButton.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review
