Repository ZeroGachis/xamarin-ui, pull requests merged in 2020-11, with the labels that each got.

#12 ✨ Add a basic Barcode Entry component.
  Smartway.UiComponent.Droid/Properties/AndroidManifest.xml
  Smartway.UiComponent.Droid/Properties/AssemblyInfo.cs
  Smartway.UiComponent.Droid/Renderers/BarcodeEntryRenderer.cs
  Smartway.UiComponent.Droid/Resources/AboutResources.txt
  Smartway.UiComponent.Droid/Resources/Resource.designer.cs
  Smartway.UiComponent.Droid/Resources/drawable/cursor.xml
  Smartway.UiComponent.Droid/Resources/values/colors.xml
  Smartway.UiComponent.Droid/Resources/values/strings.xml
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/MainActivity.cs
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample.Android/Smartway.UiComponent.Sample.Android.csproj
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent.nuspec
  Smartway.UiComponent.sln
  Smartway.UiComponent/Behaviors/BaseBehavior.cs
  Smartway.UiComponent/Inputs/Barcode/BarcodeEntry.cs
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml.cs
  Smartway.UiComponent/Inputs/Barcode/BarcodeInputBehavior.cs
  Smartway.UiComponent/Resources/Images/icon_gencode.png
  Smartway.UiComponent/Resources/Resources.Designer.cs
  Smartway.UiComponent/Resources/Resources.resx
  Smartway.UiComponent/Smartway.UiComponent.csproj
  smartway.png
Labels: Task, To Review

#14 💄 fix separators visual
  Smartway.UiComponent.Sample/Separator/SeparatorsSample.xaml
  Smartway.UiComponent/Separators/LabelledDivider.xaml
  Smartway.UiComponent/Separators/LabelledDivider.xaml.cs
Labels: bug

#13 ✨💄 add dark theme
  Smartway.UiComponent.Sample/App.xaml
  Smartway.UiComponent.Sample/Basics/BasicComponents.xaml
  Smartway.UiComponent.Sample/Basics/BasicComponents.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPage.xaml.cs
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Resources/Images/white_icon_close.png
  Smartway.UiComponent/Resources/Themes.xaml
  Smartway.UiComponent/Resources/Themes.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
Labels: To Review, enhancement

#15 Fix/expander cart list
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent.Sample/Buttons/ButtonViewModel.cs
  Smartway.UiComponent.Sample/DummyArticle.cs
  Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml
  Smartway.UiComponent.Sample/ExpanderCard/ViewModels/ExpanderCardSampleViewModel.cs
  Smartway.UiComponent.Sample/Layouts/LayoutsSample.xaml
  Smartway.UiComponent.Sample/Layouts/LayoutsSample.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/SectionSheet/ViewModels/SectionSheetSampleViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Buttons/ScanButton.xaml
  Smartway.UiComponent/Buttons/ScanButton.xaml.cs
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
  Smartway.UiComponent/CardLists/ExpanderCardList.xaml
  Smartway.UiComponent/CardLists/ExpanderCardList.xaml.cs
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml.cs
  Smartway.UiComponent/Cards/CustomExpander.xaml
  Smartway.UiComponent/Cards/ExpanderCard.xaml
  Smartway.UiComponent/Cards/ExpanderCard.xaml.cs
  Smartway.UiComponent/Layouts/ScannableLayout.xaml
  Smartway.UiComponent/Layouts/ScannableLayout.xaml.cs
  Smartway.UiComponent/Resources/Images/icon_scan.png
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review, enhancement

#17 Feature/add condensed articles property
  Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml.cs
Labels: To Review

#18 Fix/button and top bar
  Smartway.UiComponent/Buttons/Button.xaml
  Smartway.UiComponent/Cards/CustomExpander.xaml
  Smartway.UiComponent/Resources/Images/white_icon_arrow_back.png
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
Labels: To Review, bug

#20 Adapt ArticleCardList To Condensed Card option
  Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
Labels: Task, To Review

#22 Add component PluralizableLabel
  Smartway.UiComponent.Sample/Basics/BasicComponents.xaml
  Smartway.UiComponent/Labels/PluralizableLabel.xaml
  Smartway.UiComponent/Labels/PluralizableLabel.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: enhancement

#21 Fix/visual index screen
  Smartway.UiComponent.Sample/App.xaml.cs
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent.Sample/Resources/OpenSans-SemiBold.ttf
  Smartway.UiComponent.Sample/Separator/SeparatorsSample.xaml
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Buttons/Button.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ExpanderCardList.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/CustomExpander.xaml
  Smartway.UiComponent/Resources/Themes.xaml
  Smartway.UiComponent/Separators/Divider.xaml
  Smartway.UiComponent/Separators/Divider.xaml.cs
  Smartway.UiComponent/Separators/ElementSeparator.xaml
  Smartway.UiComponent/Smartway.UiComponent.csproj
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
Labels: enhancement

#26 Fix/adjust the card list articles ui
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Separators/Divider.xaml
Labels: To Review

#27 :sparkles: add nodialog datepicker
  Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample.Android/Resources/values/styles.xml
  Smartway.UiComponent/Inputs/NoDialogDatePicker.xaml
  Smartway.UiComponent/Inputs/NoDialogDatePicker.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review
