Repository ZeroGachis/xamarin-ui, pull requests merged in 2020-12, with the labels that each got.

#28 :sparkles: add custom renderer for disabled button
  Smartway.UiComponent.Droid/Renderers/CustomButtonRenderer.cs
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent/Buttons/Button.xaml
Labels: To Review

#29 ModalPage Component
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml
  Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Pages/ModalPage.xaml
  Smartway.UiComponent/Pages/ModalPage.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#30 Text Buttons + Buttons improvments
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent/Buttons/Button.xaml
  Smartway.UiComponent/Buttons/Button.xaml.cs
  Smartway.UiComponent/Buttons/ScanButton.xaml
  Smartway.UiComponent/Buttons/TextButton.xaml
  Smartway.UiComponent/Buttons/TextButton.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review, enhancement

#32 🎉 Add radio button
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/RadioButton.xaml
  Smartway.UiComponent/Inputs/RadioButton.xaml.cs
Labels: To Review, enhancement

#36 :bug: Radio buton, IsChecked property can modify the source value
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/RadioButton.xaml.cs
Labels: To Review, bug

#38 ✨ add keyboard bindable property
  Smartway.UiComponent.Sample.Android/CustomEntryRenderer.cs
  Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml
  Smartway.UiComponent/Inputs/FormEntry.xaml
  Smartway.UiComponent/Inputs/FormEntry.xaml.cs
Labels: To Review

#40 Fix/UI for family selection
  Smartway.UiComponent/Inputs/RadioButton.xaml
Labels: To Review

#41 Revert ":feature: add swipe on article card list"
  Smartway.UiComponent.Droid/Resources/Resource.designer.cs
  Smartway.UiComponent.Droid/Resources/drawable-hdpi/icon_delete.png
  Smartway.UiComponent.Droid/Resources/drawable-ldpi/icon_delete.png
  Smartway.UiComponent.Droid/Resources/drawable-mdpi/icon_delete.png
  Smartway.UiComponent.Droid/Resources/drawable-xhdpi/icon_delete.png
  Smartway.UiComponent.Droid/Resources/drawable-xxhdpi/icon_delete.png
  Smartway.UiComponent.Droid/Resources/drawable-xxxhdpi/icon_delete.png
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/MainActivity.cs
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample/ArticleCardList/ViewModels/ArticleCardListSampleViewModel.cs
  Smartway.UiComponent.Sample/ArticleCardList/Views/ArticleCardListSample.xaml
  Smartway.UiComponent.Sample/ArticleCardList/Views/ArticleCardListSample.xaml.cs
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/CardLists/ArticleCardList.xaml
  Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml.cs
Labels: bug

#42 :art: fix size and font for entry value
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml
Labels: Task, To Review, enhancement
