Repository ZeroGachis/xamarin-ui, pull requests merged in 2021-01, with the labels that each got.

#43 ✨Choice chips component
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/Chips.xaml
  Smartway.UiComponent/Inputs/Chips.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Merge, enhancement

#44 ✨ Add custom search bar
  Smartway.UiComponent.Droid/Resources/Resource.designer.cs
  Smartway.UiComponent.Droid/Resources/drawable-hdpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable-ldpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable-mdpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable-xhdpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable-xxhdpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable-xxxhdpi/icon_search.png
  Smartway.UiComponent.Droid/Resources/drawable/icon_close.png
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/SearchBar.xaml
  Smartway.UiComponent/Inputs/SearchBar.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: enhancement

#45 💄 Rename icon and improve visual
  Smartway.UiComponent.Droid/Resources/Resource.designer.cs
  Smartway.UiComponent.Droid/Resources/drawable/icon_close_grey.png
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent/Inputs/SearchBar.xaml
Labels: To Review

#46 💄 Task/review top app bar
  Smartway.UiComponent.Sample/Inputs/ViewModels/FormEntryViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent/Inputs/FormEntry.xaml
  Smartway.UiComponent/Inputs/FormEntry.xaml.cs
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
Labels: To Review

#47 :sparkles: Add binding for nodialogdatepicker
  Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
Labels: Task

#49 :lipstick: radio button place
  Smartway.UiComponent/Inputs/RadioButton.xaml
Labels: To Review

#51 :recycle: Move styling nodialog datepicker (sample => droid)
  Smartway.UiComponent.Droid/Resources/Resource.designer.cs
  Smartway.UiComponent.Droid/Resources/values/styles.xml
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample.Android/Resources/values/styles.xml
Labels: To Review

#52 ✨ Add new status colors
  Smartway.UiComponent.Sample/Indicators/Views/Indicators.xaml
  Smartway.UiComponent/Indicators/Status.xaml
  Smartway.UiComponent/Indicators/Status.xaml.cs
Labels: Task, To Review, enhancement

#53 Feature/nodialog datepicker integration
  Smartway.UiComponent.Droid/Assets/OpenSans-Bold.ttf
  Smartway.UiComponent.Droid/Assets/OpenSans-SemiBold.ttf
  Smartway.UiComponent.Droid/Resources/font/open_sans.xml
  Smartway.UiComponent.Droid/Resources/font/open_sans_regular.ttf
  Smartway.UiComponent.Droid/Resources/values/styles.xml
  Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/RoundedDatePicker.xaml
  Smartway.UiComponent/Inputs/RoundedDatePicker.xaml.cs
Labels: To Review, enhancement
