Repository ZeroGachis/xamarin-ui, pull requests merged in 2021-02, with the labels that each got.

#54 remove copy/paste bug, improve form entry and add password entry
  Smartway.UiComponent.Sample.Android/CustomEntryRenderer.cs
  Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
  Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml
  Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml.cs
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Inputs/FormEntry.xaml
  Smartway.UiComponent/Inputs/FormEntry.xaml.cs
Labels: To Review, enhancement

#56 ✨ Improve SearchBar with commands and bindings
  Smartway.UiComponent.Sample.Android/Smartway.UiComponent.Sample.Android.csproj
  Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml.cs
  Smartway.UiComponent/Inputs/SearchBar.xaml
  Smartway.UiComponent/Inputs/SearchBar.xaml.cs
Labels: Task, To Review, enhancement

#57 :bug: TwoWay BindingMode RoundedDatePicker
  Smartway.UiComponent/Inputs/RoundedDatePicker.xaml.cs
Labels: bug

#59 💄 Add Icon component
  Smartway.UiComponent.Droid/Assets/MaterialIcons-Regular.ttf
  Smartway.UiComponent/Labels/Icons/Icon.xaml
  Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#60 ✨create ClickableItem
  Smartway.UiComponent.Sample/Layouts/LayoutsSample.xaml
  Smartway.UiComponent/Layouts/ClickableItem.xaml
  Smartway.UiComponent/Layouts/ClickableItem.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review

#61 💄 Update all code to use Colors.xaml resource
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent.Sample/Theme.xaml
  Smartway.UiComponent/Buttons/Button.xaml
  Smartway.UiComponent/Buttons/ScanButton.xaml
  Smartway.UiComponent/Buttons/TextButton.xaml
  Smartway.UiComponent/Cards/ArticleCard.xaml
  Smartway.UiComponent/Cards/CustomExpander.xaml
  Smartway.UiComponent/Indicators/Status.xaml
  Smartway.UiComponent/Inputs/Chips.xaml
  Smartway.UiComponent/Inputs/FormEntry.xaml
  Smartway.UiComponent/Inputs/RadioButton.xaml
  Smartway.UiComponent/Resources/Colors.xaml
  Smartway.UiComponent/Resources/Colors.xaml.cs
  Smartway.UiComponent/Separators/Divider.xaml
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#62 🐛 fix position label with no image
  Smartway.UiComponent.Sample/TopAppBar/Views/TopAppBar.xaml
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
Labels: To Review

#67 Clean resources and use Icon font
  Smartway.UiComponent.Sample/App.xaml.cs
  Smartway.UiComponent.Sample/Basics/BasicComponents.xaml
  Smartway.UiComponent.Sample/Resources/OpenSans-Bold.ttf
  Smartway.UiComponent.Sample/Resources/OpenSans-SemiBold.ttf
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/AssemblyInfo.cs
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml
  Smartway.UiComponent/Resources/Fonts/OpenSans-Bold.ttf
  Smartway.UiComponent/Resources/Fonts/OpenSans-Regular.ttf
  Smartway.UiComponent/Resources/Fonts/OpenSans-SemiBold.ttf
  Smartway.UiComponent/Resources/Icons/orange_icon_arrow_down.png
  Smartway.UiComponent/Resources/Icons/orange_icon_warning.png
  Smartway.UiComponent/Resources/Images/icon_gencode.png
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: Task, To Review

#66 Feature/use icon on topappbar
  Smartway.UiComponent.Sample/TopAppBar/Views/TopAppBar.xaml
  Smartway.UiComponent/Buttons/ScanButton.xaml
  Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
  Smartway.UiComponent/Resources/Images/icon_arrow_back.png
  Smartway.UiComponent/Resources/Images/icon_close.png
  Smartway.UiComponent/Resources/Images/icon_scan.png
  Smartway.UiComponent/Resources/Images/white_icon_arrow_back.png
  Smartway.UiComponent/Resources/Images/white_icon_close.png
  Smartway.UiComponent/Smartway.UiComponent.csproj
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
Labels: To Review

#68 Add missing icons
  Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
Labels: Task, To Review

#69 Task/transform modal page into modal
  Smartway.UiComponent.Sample/Buttons/Button.xaml
  Smartway.UiComponent.Sample/Layouts/LayoutsSample.xaml
  Smartway.UiComponent.Sample/MainPage.xaml
  Smartway.UiComponent.Sample/MainPageViewModel.cs
  Smartway.UiComponent.Sample/Pages/DefaultModal.xaml
  Smartway.UiComponent.Sample/Pages/DefaultModal.xaml.cs
  Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml
  Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml.cs
  Smartway.UiComponent.Sample/Pages/ModalSample.xaml
  Smartway.UiComponent.Sample/Pages/ModalSample.xaml.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Buttons/TextButton.xaml
  Smartway.UiComponent/Buttons/TextButton.xaml.cs
  Smartway.UiComponent/Layouts/ClickableItem.xaml
  Smartway.UiComponent/Layouts/ClickableItem.xaml.cs
  Smartway.UiComponent/Pages/Modal.xaml
  Smartway.UiComponent/Pages/Modal.xaml.cs
  Smartway.UiComponent/Pages/ModalPage.xaml
  Smartway.UiComponent/Pages/ModalPage.xaml.cs
  Smartway.UiComponent/Pages/YesModalFooter.xaml
  Smartway.UiComponent/Pages/YesModalFooter.xaml.cs
  Smartway.UiComponent/Pages/YesNoModalFooter.xaml
  Smartway.UiComponent/Pages/YesNoModalFooter.xaml.cs
  Smartway.UiComponent/Separators/Divider.xaml
  Smartway.UiComponent/Smartway.UiComponent.csproj
  Smartway.UiComponent/TopAppBar/TopAppBar.xaml
Labels: To Review, enhancement

#71 Task/create modal dialog
  Smartway.UiComponent.Sample/Pages/DefaultModal.xaml
  Smartway.UiComponent.Sample/Pages/DefaultModal.xaml.cs
  Smartway.UiComponent.Sample/Pages/ModalDialogSample.xaml
  Smartway.UiComponent.Sample/Pages/ModalDialogSample.xaml.cs
  Smartway.UiComponent.Sample/Pages/ModalSample.xaml
  Smartway.UiComponent.Sample/Pages/ModalSample.xaml.cs
  Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
  Smartway.UiComponent/Pages/ModalDialog.xaml
  Smartway.UiComponent/Pages/ModalDialog.xaml.cs
  Smartway.UiComponent/Smartway.UiComponent.csproj
Labels: To Review, enhancement

#73 :lipstick: Add Dark Theme Colors
  Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml
  Smartway.UiComponent/Inputs/Chips.xaml
  Smartway.UiComponent/Resources/Colors.xaml
  Smartway.UiComponent/Resources/Themes.xaml
  Smartway.UiComponent/Separators/LabelledDivider.xaml
Labels: To Review

#75 💄 rename dark theme colors
  Smartway.UiComponent/Inputs/Barcode/BarcodeInput.xaml
  Smartway.UiComponent/Resources/Colors.xaml
  Smartway.UiComponent/Resources/Themes.xaml
  Smartway.UiComponent/Separators/LabelledDivider.xaml
Labels: To Review
